edit output v9

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -121,13 +121,13 @@ jobs:
         run: terraform validate
         working-directory: implementation
 
-      - name: Prevent Destructive Changes
-        run: |
-          if terraform show -json tfplan | jq -e '.resource_changes[] | select(.change.actions[] == "delete")' > /dev/null; then
-            echo "❌ ABORTING: Destructive changes detected!"
-            exit 1
-          fi
-        working-directory: implementation
+      # - name: Prevent Destructive Changes
+      #   run: |
+      #     if terraform show -json tfplan | jq -e '.resource_changes[] | select(.change.actions[] == "delete")' > /dev/null; then
+      #       echo "❌ ABORTING: Destructive changes detected!"
+      #       exit 1
+      #     fi
+      #   working-directory: implementation
 
       - name: Terraform Plan
         working-directory: implementation
